name: Linting Latex

on:
  pull_request:
    branches: [ main ]
    paths:
      - "src/**"
      - "entrypoint.pdf"

jobs:
  latex_linting:
    runs-on: ubuntu-latest
    steps:
      - name: skip
        if: contains( github.head_ref, 'automation')
        runs: true
      - name: checkout repo
        if: contains( github.head_ref, 'automation') == false
        uses: actions/checkout@v2
      - name: cleaning
        if: contains( github.head_ref, 'automation') == false
        run: |
          source automation
          clean
      - name: linting latex
        uses: j2kun/chktex-action@1.0.3
