name: Linting Latex

on:
  pull_request:
    branches: [ main ]
    paths:
      - "src/**"
      - "entrypoint.pdf"

if: contains( github.head_ref, 'automation') == false
jobs:
  latex_linting_skip:
    runs-on: ubuntu-latest
    steps:
      - name: skip
        run: true

if: contains( github.head_ref, 'automation') == false
jobs:
  latex_linting:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: cleaning
        run: |
          source automation
          clean
      - name: linting latex
        uses: j2kun/chktex-action@1.0.3
