name: Rendering latex

on:
  pull_request:
    branches: [main]

jobs:
  latex_rendering:
    runs-on: ubuntu-latest
    steps:
      - name: check refs
        run: |
          echo ${{ github.head_ref }} asdfsdf
          #- uses: actions/checkout@v2
          #- name: linting latex
          #uses: j2kun/chktex-action@1.0.3
    
          #- name: prepare intermediate files
          #run: |
          #source automation
          #build
          #- name: rendering pdf
          #uses: xu-cheng/latex-action@v2
          #with:
          #working_directory: "./out/"
          #root_file: |
          #  entrypoint.tex
          #- name: pull-request
          #uses: repo-sync/pull-request@v2
          #with:
          #destination_branch: "main"
          #github_token: ${{ secrets.GITHUB_TOKEN }}
          #- name: clean files
          #run: |
          #cp out/entrypoint.pdf .
          #source automation
          #clean
          #git status
