name: Rendering latex

on:
  push:
    branches: [main]
    paths:
      - "src/**"
    if: contains( github.head_ref, 'automation') == false

jobs:
  latex_rendering:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: prepare intermediate files
        run: |
          source automation
          build
      - name: rendering pdf
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: "./out/"
          root_file: |
            entrypoint.tex
      - name: clean files
        run: |
          cp out/entrypoint.pdf .
          source automation
          clean
            git status
      - name: commit changes
        run: |
          git config --global user.name  'Github Action'
          git config --global user.email 'action-bot@github.com'         
          git checkout automation/latex
          git commit -am "Automated rendering"
          git push origin automation/latex
      - name: pull requests
        uses: repo-sync/pull-request@v2
        with:
          source_branch: automation/latex
          destination_branch: main
          pr_title: "Latex rendering"
          pr_body: ":robot: latex rendering automation"
          github_token: ${{ secrets.GITHUB_TOKEN }}


