name: Render Latex Pdf

on:
  push:
    branches: [ main ]

jobs:
  latex_rendering:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        #- name: linting latex
        #uses: j2kun/chktex-action@1.0.3
        #if: ${{ success() }} || ${{ failure() }}
      - name: prepare intermediate files
        run: |
          source automation
          build
      - name: rendering pdf 
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: "${{ env.GITHUB_WORKSPACE}}/out/"
          root_file: |
            entrypoint.tex
      - name: clean files
        run: |
          cp out/entrypoint.pdf .
          source automation
          clean
          git status

